version: '3.8'

services:
  frontend:
    build:
      context: ../payment-form
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../payment-form:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: yarn dev
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: yarn start:dev